#!/bin/bash
# Auto-generated script for crates.io
# Generated from: crates.md
# Mirror ID: crates.io

gen_tag="Generated by hust-mirrors auto script"

check() {
	has_command cargo
}

_crates.io_install_1() {
	# Execute commands
	# Execute commands
	mkdir -p "${HOME}/.cargo"
	if [ -f "${HOME}/.cargo/config.toml" ]; then
	confirm "You already have a config.toml file in your cargo home, do you want to continue?" || \
	return 1
	mv "${HOME}/.cargo/config.toml" "${_backup_dir}/cargo.bak"
	else
	touch "${_backup_dir}/cargo.bak"
	fi
	version=$(cargo --version 2>/dev/null | cut -f 2 -d " ")
	if [ -n "$version" ] && \
	[ $(echo "$version" | cut -f 1 -d ".") -ge 1 ] && \
	[ $(echo "$version" | cut -f 2 -d ".") -ge 68 ]; then
	_crates_mirror="sparse+${http}://${domain}/crates.io-index/"
	else
	_crates_mirror="${http}://${domain}/git/crates.io-index/"
	fi
	cat >"${HOME}/.cargo/config.toml" <<EOF
# ${gen_tag}
[source.crates-io]
replace-with = 'hustmirror'
[source.hustmirror]
registry = "${_crates_mirror}"
EOF

	return 0
}

install() {

	_crates.io_install_1 || return 1
	print_success "Mirror configuration updated successfully"
}

uninstall() {
	# Recover from backup files and execute recovery commands
	print_info "Starting recovery process..."


	# Execute recovery commands
	mv "$_backup_dir/cargo.bak" "${HOME}/.cargo/config" 2>/dev/null || true

	print_success "Recovery completed"
}
