name: Build

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
