name: Test CLI Generation

on:
  pull_request:
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test generation
        run: python scripts/parser.py -t -v
